"""
Agent Database Schema for Friday AI
====================================

Schema for autonomous agent system including:
- Friday Suggestions (script improvement backlog)
- Analysis runs tracking
- Agent task history
"""

from __future__ import annotations
from datetime import datetime
from typing import Optional, List
from enum import Enum

from sqlalchemy import (
    JSON,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    Float,
    Boolean,
    Index,
    ARRAY,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


# ============================================================================
# ENUMS
# ============================================================================


class SuggestionType(str, Enum):
    """Types of suggestions Friday can make"""

    PLOT_INCONSISTENCY = "plot_inconsistency"
    CHARACTER_ARC_GAP = "character_arc_gap"
    DIALOGUE_IMPROVEMENT = "dialogue_improvement"
    PACING_ISSUE = "pacing_issue"
    TRANSITION_MISSING = "transition_missing"
    SETUP_PAYOFF_MISSING = "setup_payoff_missing"
    CONTINUITY_ERROR = "continuity_error"
    STRUCTURE_SUGGESTION = "structure_suggestion"
    DRAFT_SCENE = "draft_scene"
    RESEARCH_FINDING = "research_finding"


class SuggestionStatus(str, Enum):
    """Status of a suggestion"""

    PENDING = "pending"
    DISCUSSED = "discussed"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    DEFERRED = "deferred"
    APPLIED = "applied"


class SuggestionCategory(str, Enum):
    """Category for grouping suggestions"""

    SCREENPLAY = "screenplay"
    DIALOGUE = "dialogue"
    PACING = "pacing"
    CHARACTER = "character"
    STRUCTURE = "structure"
    RESEARCH = "research"
    GENERAL = "general"


class AnalysisTrigger(str, Enum):
    """What triggered an analysis run"""

    SCHEDULED = "scheduled"  # Nightly scheduled run
    ON_EDIT = "on_edit"  # Triggered after scene edit
    ON_REQUEST = "on_request"  # Boss explicitly requested


# ============================================================================
# FRIDAY SUGGESTIONS
# ============================================================================


class FridaySuggestion(Base):
    """
    Suggestions generated by Friday's autonomous analysis.

    These are improvements, issues, or draft content that Friday
    prepares in the background for Boss to review.
    """

    __tablename__ = "friday_suggestions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Project reference (from screenplay_schema)
    project_id: Mapped[int] = mapped_column(Integer, nullable=False)

    # Scene reference (NULL if project-level suggestion)
    scene_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    # Suggestion content
    suggestion_type: Mapped[str] = mapped_column(
        String(64), nullable=False, default=SuggestionType.STRUCTURE_SUGGESTION.value
    )
    title: Mapped[str] = mapped_column(String(256), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)

    # Proposed change (if applicable)
    # For draft_scene: Full scene content
    # For dialogue_improvement: New dialogue text
    # For structure_suggestion: Reorder instructions
    proposed_change: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Affected scenes (list of scene IDs)
    affected_scenes: Mapped[List[int]] = mapped_column(JSON, default=list)

    # Priority & categorization
    priority: Mapped[int] = mapped_column(Integer, default=3)  # 1=critical, 5=minor
    category: Mapped[str] = mapped_column(
        String(64), default=SuggestionCategory.GENERAL.value
    )
    confidence: Mapped[float] = mapped_column(Float, default=0.5)  # 0-1

    # Status tracking
    status: Mapped[str] = mapped_column(
        String(32), default=SuggestionStatus.PENDING.value
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    discussed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    resolved_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    # Resolution notes (when accepted/rejected/deferred)
    decision_notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Source tracking
    analysis_run_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    trigger: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    __table_args__ = (
        Index("ix_suggestions_project_status", "project_id", "status"),
        Index("ix_suggestions_priority", "priority", "created_at"),
        Index("ix_suggestions_type", "suggestion_type"),
    )


# ============================================================================
# ANALYSIS RUN TRACKING
# ============================================================================


class AnalysisRun(Base):
    """
    Track each analysis run for auditing and debugging.
    """

    __tablename__ = "analysis_runs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Run identifier
    run_id: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)

    # What was analyzed
    project_id: Mapped[int] = mapped_column(Integer, nullable=False)
    scene_ids: Mapped[Optional[List[int]]] = mapped_column(JSON, nullable=True)

    # What triggered it
    trigger: Mapped[str] = mapped_column(String(64), nullable=False)

    # Configuration used
    config: Mapped[dict] = mapped_column(JSON, default=dict)

    # Results summary
    suggestions_generated: Mapped[int] = mapped_column(Integer, default=0)
    suggestions_deduplicated: Mapped[int] = mapped_column(Integer, default=0)

    # Timing
    started_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    duration_seconds: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # Status
    status: Mapped[str] = mapped_column(
        String(32), default="running"
    )  # running, completed, failed
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    __table_args__ = (Index("ix_analysis_runs_project", "project_id", "started_at"),)


# ============================================================================
# FACE PROFILES (for camera/access control)
# ============================================================================


class FaceProfile(Base):
    """
    Face recognition profiles for access control.
    """

    __tablename__ = "face_profiles"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Identity
    name: Mapped[str] = mapped_column(String(128), nullable=False)
    access_level: Mapped[str] = mapped_column(
        String(32), default="team"
    )  # boss, team, unknown

    # Face data
    embedding: Mapped[Optional[bytes]] = mapped_column(
        nullable=True
    )  # Face embedding vector
    reference_images: Mapped[List[str]] = mapped_column(
        JSON, default=list
    )  # Paths to reference images

    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    last_seen: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    __table_args__ = (
        Index("ix_face_profiles_name", "name"),
        Index("ix_face_profiles_access", "access_level"),
    )


class FaceAccessLog(Base):
    """
    Log of face recognition events for auditing.
    """

    __tablename__ = "face_access_log"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Who
    face_profile_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("face_profiles.id"), nullable=True  # NULL for unknown faces
    )

    # When/where
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    location: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    # Recognition details
    confidence: Mapped[float] = mapped_column(Float, default=0.0)
    emotion: Mapped[Optional[str]] = mapped_column(String(32), nullable=True)

    # What happened
    action_taken: Mapped[str] = mapped_column(String(64), nullable=False)
    # granted_access, denied_access, captured_unknown, session_started

    # Relationship
    face_profile: Mapped[Optional[FaceProfile]] = relationship()

    __table_args__ = (Index("ix_face_access_timestamp", "timestamp"),)
