#!/bin/bash
# AWS Configuration Guide

echo "🔧 AWS CLI Configuration"
echo "========================"
echo ""
echo "Run this command and enter your credentials:"
echo ""
echo "aws configure"
echo ""
echo "You'll be prompted for:"
echo "AWS Access Key ID [None]: YOUR_ACCESS_KEY_ID_HERE"
echo "AWS Secret Access Key [None]: YOUR_SECRET_ACCESS_KEY_HERE" 
echo "Default region name [None]: us-east-1"
echo "Default output format [None]: json"
echo ""
echo "Example:"
echo "AWS Access Key ID [None]: AKIAIOSFODNN7EXAMPLE"
echo "AWS Secret Access Key [None]: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
echo "Default region name [None]: us-east-1"
echo "Default output format [None]: json"
echo ""
echo "✅ After setup, test with:"
echo "aws sts get-caller-identity"
